name: Hello Actions Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello Actions
        run: echo "Hello Github actions"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye Actions
        run: echo "Goodbye world"
        shell: bash
