name: Issue Comment Workflow

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      run: |
        gh api -X POST \
        https://api.github.com/${ORGNIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
        -f body='
        Comment from api call
        '
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGNIZATION: ${{ github.event.orginisation.login }}
        REPOSITORY: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        
        

